### ISSUE TITLE
Error with pathing?

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#146]
[08:14:32]16778331 W27N77 planer-573           [room W27N77 pos 20,34] No routing why?
[08:14:32]16778331 W27N77 planer-573           [room W27N77 pos 20,34] Executing creep role failed: W27N77 planer-573 587c70b9ae39e11d73f7d7f7 {"x":20,"y":34,"roomName":"W27N77"} Error
Error
    at Creep.getRoute (prototype_creep_routing:7:11)
    at Creep.followPath (prototype_creep_routing:183:20)
    at Creep.handle (prototype_creep:54:16)
    at Room.execute (prototype_room:14:13)
    at Memory.myRooms._.map._.filter.r (main:33:54)
    at /opt/engine/node_modules/lodash/index.js:1932:13
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
    at baseFilter (/opt/engine/node_modules/lodash/index.js:1931:7)
[08:14:36]planer-573 Not in Game.creeps 145 W27N77
[08:14:36]16778332 W27N77                      Spawn from creepsConfig: planer
[08:14:40]16778333 W27N77                      Spawn from creepsConfig: planer
[08:14:44]16778334 W27N77                      Spawn from creepsConfig: planer

**Comment by TooAngel** [comment]
Still an issue?
