### ISSUE TITLE
Another error with helpers

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#154]
[06:26:37]16864200 W29N76                      Executing room failed: W29N76 TypeError: this.findRoute is not a function TypeError: this.findRoute is not a function
    at Room.checkCanHelp (prototype_room_my:245:22)
    at Room.checkForEnergyTransfer (prototype_room_my:274:24)
    at Room.executeRoom (prototype_room_my:410:8)
    at Room.myHandleRoom (prototype_room_my:36:15)
    at Room.handle (prototype_room:5:17)
    at Room.execute (prototype_room:12:27)
    at Memory.myRooms._.map._.filter.r (main:34:54)
    at /opt/engine/node_modules/lodash/index.js:1932:13
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)

**Comment by Somotaw** [comment]
[06:26:37]16864200 W27N77                      Executing room failed: W27N77 TypeError: this.findRoute is not a function TypeError: this.findRoute is not a function
    at Room.checkCanHelp (prototype_room_my:245:22)
    at Room.checkForEnergyTransfer (prototype_room_my:274:24)
    at Room.executeRoom (prototype_room_my:410:8)
    at Room.myHandleRoom (prototype_room_my:36:15)
    at Room.handle (prototype_room:5:17)
    at Room.execute (prototype_room:12:27)
    at Memory.myRooms._.map._.filter.r (main:34:54)
    at /opt/engine/node_modules/lodash/index.js:1932:13
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)

**Comment by TooAngel** [comment]
@Nevrdid @Somotaw Still an issue?

**Comment by Nevrdid** [comment]
not for me
