### ISSUE TITLE
"needHelp" Error

### ISSUE THREAD

**Issue by totalschaden** [TooAngel/screeps#164]
Executing room failed: W81N49 TypeError: Cannot read property 'needHelp' of undefined TypeError: Cannot read property 'needHelp' of undefined
    at Room.checkCanHelp (prototype_room_my:232:49)
    at Room.checkForEnergyTransfer (prototype_room_my:274:24)
    at Room.executeRoom (prototype_room_my:410:8)
    at Room.myHandleRoom (prototype_room_my:36:15)
    at Room.handle (prototype_room:5:17)
    at Room.execute (prototype_room:13:27)
    at Memory.myRooms._.map._.filter.r (main:59:54)
    at /opt/engine/node_modules/lodash/index.js:1932:13
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)

**Comment by TooAngel** [comment]
@Nevrdid can you check this?

**Comment by Nevrdid** [comment]
yeah, sorry less active these days. As i'm not o my computer. i think this should fix it : 
`if (!nearestRoom || (nearestRoom && !Memory.rooms[nearestRoom].needHelp)) {`
But also think that i should be better to check that into needHelp function.
Dunno when i'll can look at it so i think just give the fix here is enouth until i'll do a PR with improved need/canHelp functions for avoid these issues.
ps : when this king of issue come totalschaden (Cannot read property ... of undefined), it's that method object don't exist, just have to skip mehod use for undefined objects to quickly fix.
