### ISSUE TITLE
scout causing crashes after recent push

### ISSUE THREAD

**Issue by ikiris** [TooAngel/screeps#232]
18145254 E64S82 scout-260            [room E64S82 pos 37,0] search: [room E65S82 pos 25,25] TypeError: Cannot read property 'x' of undefined TypeError: Cannot read property 'x' of undefined
    at Room.updatePosition (prototype_room_routing:105:33)
    at Room.getCostMatrixCallback (prototype_room_costmatrix:7:10)
    at breadthFirstSearch (role_scout:92:36)
    at Object.roles.scout.execute (role_scout:142:10)
    at Creep.handle (prototype_creep:64:12)
    at Room.execute (prototype_room:19:13)
    at Memory.myRooms._.filter.r (main:35:48)
    at /opt/engine/node_modules/lodash/index.js:1932:13
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)

**Comment by ikiris** [comment]
more generally, the cached pathing seems to become broken often and needs to be purged. Something isn't right but I haven't found where the problem is yet.

**Comment by TooAngel** [comment]
Problem still exist? Check my workspace branch
