### ISSUE TITLE
setCostMatrixStructures is not a function

### ISSUE THREAD

**Issue by Brutalbic** [TooAngel/screeps#247]
I'm using the latest respository ef48135, and I am getting this error every time it tries to execute this function.
I don't understand it well enough to be able to fix it myself.

```
Executing room failed: W3N18 TypeError: this.setCostMatrixStructures is not a function TypeError: this.setCostMatrixStructures is not a function
    at roomCallback (prototype_room_external:7:10)
    at /usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/path-finder.js:125:31
    at Object.exports.search (/usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/path-finder.js:137:19)
    at Object. (/usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/game/path-finder.js:54:38)
    at Object.search (evalmachine.:1:72)
    at Room.checkBlocked (prototype_room_external:23:31)
    at Room.externalHandleRoom (prototype_room_external:53:24)
    at Room.handle (prototype_room:11:15)
    at Room.execute (prototype_room:21:27)
    at Memory.myRooms._.filter.r (main:35:48)
```

**Comment by Brutalbic** [comment]
Edited title/post because the issue I thought this was related to has already been fixed. However, this same error message above just happened to me a few seconds ago while editing this post.
```Executing room failed: W2N16 TypeError: this.setCostMatrixStructures is not a function TypeError: this.setCostMatrixStructures is not a function
    at roomCallback (prototype_room_external:7:10)
    at /usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/path-finder.js:125:31
    at Object.exports.search (/usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/path-finder.js:137:19)
    at Object. (/usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/game/path-finder.js:54:38)
    at Object.search (evalmachine.:1:72)
    at Room.checkBlocked (prototype_room_external:23:31)
    at Room.externalHandleRoom (prototype_room_external:53:24)
    at Room.handle (prototype_room:11:15)
    at Room.execute (prototype_room:21:27)
    at Memory.myRooms._.filter.r (main:35:48)```

**Comment by baileyherbert** [comment]
Just got this as well.

Executing room failed: W96N13 TypeError: this.setCostMatrixStructures is not a function TypeError: this.setCostMatrixStructures is not a function
    at roomCallback (prototype_room_external:7:10)
    at /opt/engine/dist/core/path-finder.js:117:31
    at Object.exports.search (/opt/engine/dist/core/path-finder.js:129:19)
    at Object. (/opt/engine/dist/game/path-finder.js:54:38)
    at Object.search (evalmachine.:1:72)
    at Room.checkBlocked (prototype_room_external:23:3

**Comment by TooAngel** [comment]
Could you test https://github.com/TooAngel/screeps/pull/250 and see if it still occurs?

**Comment by baileyherbert** [comment]
The error was very scarce and seemingly random so I'll let you know if I see it pop up again. :)
