### ISSUE TITLE
MemorySegmentError - mostly (or only) for carrys

### ISSUE THREAD

**Issue by mschultheiss83** [TooAngel/screeps#487]
i'm getting MemorySegmentError mostly (only) for carrys

```
Executing creep role failed: W3S9 carry-2144 5a11e77a202f8646e87f39cf {"x":0,"y":39,"roomName":"W3S9"} MemorySegmentError
MemorySegmentError
    at Object.brain.checkSegmentActive (config_brain_memory:318:11)
    at Object.brain.getSegment (config_brain_memory:345:11)
    at Object.brain.prepareSegmentObjectMemory (config_brain_memory:279:25)
    at Object.brain.getSegmentObject (config_brain_memory:393:9)
    at Room.getMemoryCostMatrix (prototype_room_memory:59:16)
    at Room.getCostMatrixCal...
```

**Comment by mschultheiss83** [comment]
@TooAngel do we have some debug functions to see whats in there and whats not working or why?

**Comment by samogot** [comment]
MemorySegmentError can be safely suppressed. it's just skipping a tick to switch segment
Or you can set segments usage to 10 in config

**Comment by Pyrockk** [comment]
I get this error a lot of the time when using the squad functions - specifically on my healers
If it were just a memory error or w/e that would be fine but it halts the creep, and they dont do anything and block the pathways.
IE
2141587 W29N34 squadheal-6940       [room W29N34 pos 9,7] Executing creep role failed: W29N34 squadheal-6940 5a45cdf6a5b835370a6bb775 {"x":9,"y":7,"roomName":"W29N34"} TypeError: Cannot read property 'x' of undefined
TypeError: Cannot read property 'x' of undefined
    at Object.Creep.squadMove (prototype_creep_squad:7:48)
    at Object.roles.squadheal.preMove (role_squadheal:65:17)
    at Object.Creep.followPath (prototype_creep_routing:201:59)
    at Object.Creep.handle (prototype_creep:104:16)
    at Object.Room.execute (prototype_room:19:13)
    at Memory.myRooms._.filter (main:51:50)
    at /opt/engine/node_modules/lodash/index.js:1932:13
    at /opt/engine/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)
    at /opt/engine/node_modules/lodash/index.js:3043:18
