### ISSUE TITLE
Fresh start error

### ISSUE THREAD

**Issue by Tsungen** [TooAngel/screeps#63]
Im getting this error after setting my spawn with a clean memory.

```
[5:17:15 AM]127048 W5N8                        Executing room failed: W5N8 TypeError: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
    at Room.myHandleRoom (prototype_room_my:39:65)
    at Room.handle (prototype_room:5:17)
    at Room.execute (prototype_room:13:27)
    at Memory.myRooms._.map._.filter (main:30:56)
    at G:\Steam\steamapps\common\Screeps\server\node_modules\lodash\index.js:1932:13
    at G:\Steam\steamapps\common\Screeps\server\node_modules\lodash\index.js:3073:15
    at baseForOwn (G:\Steam\steamapps\common\Screeps\server\node_modules\lodash\index.js:2046:14)
    at G:\Steam\steamapps\common\Screeps\server\node_modules\lodash\index.js:3043:18
    at baseFilter (G:\Steam\steamapps\common\Screeps\server\node_modules\lodash\index.js:1931:7)
    at Function.filter (G:\Steam\steamapps\common\Screeps\server\node_modules\lodash\index.js:6309:14)
```

**Comment by TooAngel** [comment]
I guess this is because the queue is not initialized, yet.

Quick fix, just add a check before that line (https://github.com/TooAngel/screeps/blob/master/src/prototype_room_my.js#L39) if queue is an array, if not create it.

Proper fix: check that the queue exist at the beginning of the `myHandleRoom` method.

**Comment by mschultheiss83** [comment]
Hint: wipe out your Memory (by http://support.screeps.com/hc/en-us/articles/205619121-RawMemory#set before testing this scripts)

```js
RawMemory.set(JSON.stringify({
 rooms:{},
 creeps:{},
 myRooms: :[],
 .... }));
```

@TooAngel maybe add a todo config_brain_memory a wipeMemory function 
to init all used custom memory keys?

**Comment by Tsungen** [comment]
got another workaround. just place the stats thingy at the end of 

`Room.prototype.executeRoom = function()`

and all will be fine :)

**Comment by TooAngel** [comment]
Are the comments now fixed due to the PR? Or should we reopen the issue?

**Comment by Tsungen** [comment]
Got no error on respawning with clear memory.
